services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=HPlayerDB
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=himagi
    user: root
    ports:
      - '5433:5432'